/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "API": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "AudioStorage": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "BigSpellaDB": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.aws.Postgres"
      "username": string
    }
    "DictionaryApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IdentityPool": {
      "id": string
      "type": "sst.aws.CognitoIdentityPool"
    }
    "Network": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "OpenAIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ThesaurusApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UserPool": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "UserPoolClient": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
